In [139]:
#загружаю данные, с учетом нестандартного разделителя ";"
import pandas
data = pandas.read_csv('dataset_Facebook.csv',sep=';')
data.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [140]:
#вычисляю среднее значение по всем числовым столбцам
data.mean(numeric_only=True)

Page total likes                                                       123194.176000
Category                                                                    1.880000
Post Month                                                                  7.038000
Post Weekday                                                                4.150000
Post Hour                                                                   7.840000
Paid                                                                        0.278557
Lifetime Post Total Reach                                               13903.360000
Lifetime Post Total Impressions                                         29585.948000
Lifetime Engaged Users                                                    920.344000
Lifetime Post Consumers                                                   798.772000
Lifetime Post Consumptions                                               1415.130000
Lifetime Post Impressions by people who have liked your Page            16766.376000
Lifetime Post reach by people who like your Page                         6585.488000
Lifetime People who have liked your Page and engaged with your post       609.986000
comment                                                                     7.482000
like                                                                      177.945892
share                                                                      27.266129
Total Interactions                                                        212.120000
dtype: float64

In [141]:
#вычисляю минимальное значение по всем числовым столбцам
data.min(numeric_only=True)

Page total likes                                                       81370.0
Category                                                                   1.0
Post Month                                                                 1.0
Post Weekday                                                               1.0
Post Hour                                                                  1.0
Paid                                                                       0.0
Lifetime Post Total Reach                                                238.0
Lifetime Post Total Impressions                                          570.0
Lifetime Engaged Users                                                     9.0
Lifetime Post Consumers                                                    9.0
Lifetime Post Consumptions                                                 9.0
Lifetime Post Impressions by people who have liked your Page             567.0
Lifetime Post reach by people who like your Page                         236.0
Lifetime People who have liked your Page and engaged with your post        9.0
comment                                                                    0.0
like                                                                       0.0
share                                                                      0.0
Total Interactions                                                         0.0
dtype: float64

In [142]:
#вычисляю максимальное значение по всем числовым столбцам
data.max(numeric_only=True)

Page total likes                                                        139441.0
Category                                                                     3.0
Post Month                                                                  12.0
Post Weekday                                                                 7.0
Post Hour                                                                   23.0
Paid                                                                         1.0
Lifetime Post Total Reach                                               180480.0
Lifetime Post Total Impressions                                        1110282.0
Lifetime Engaged Users                                                   11452.0
Lifetime Post Consumers                                                  11328.0
Lifetime Post Consumptions                                               19779.0
Lifetime Post Impressions by people who have liked your Page           1107833.0
Lifetime Post reach by people who like your Page                         51456.0
Lifetime People who have liked your Page and engaged with your post       4376.0
comment                                                                    372.0
like                                                                      5172.0
share                                                                      790.0
Total Interactions                                                        6334.0
dtype: float64

In [143]:
#вычисляю медиану по всем числовым столбцам
data.median(numeric_only=True)

Page total likes                                                       129600.0
Category                                                                    2.0
Post Month                                                                  7.0
Post Weekday                                                                4.0
Post Hour                                                                   9.0
Paid                                                                        0.0
Lifetime Post Total Reach                                                5281.0
Lifetime Post Total Impressions                                          9051.0
Lifetime Engaged Users                                                    625.5
Lifetime Post Consumers                                                   551.5
Lifetime Post Consumptions                                                851.0
Lifetime Post Impressions by people who have liked your Page             6255.5
Lifetime Post reach by people who like your Page                         3417.0
Lifetime People who have liked your Page and engaged with your post       412.0
comment                                                                     3.0
like                                                                      101.0
share                                                                      19.0
Total Interactions                                                        123.5
dtype: float64

In [144]:
#вычисляю моду по всем числовым столбцам
#для некоторых столбцов мода может быть не одна, так как некоторые значения встречаются с одинаковой частотой
data.mode(numeric_only=True)

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,136393.0,1.0,10.0,7.0,3.0,0.0,677.0,4372.0,537.0,182.0,431.0,1210.0,690,403.0,0.0,98.0,13.0,0.0
1,NaN,NaN,NaN,NaN,NaN,NaN,2232.0,6503.0,NaN,298.0,513.0,1284.0,704,NaN,NaN,NaN,14.0,39.0
2,NaN,NaN,NaN,NaN,NaN,NaN,2645.0,7004.0,NaN,319.0,599.0,2541.0,1228,NaN,NaN,NaN,NaN,75.0
3,NaN,NaN,NaN,NaN,NaN,NaN,2938.0,8533.0,NaN,322.0,652.0,2888.0,1640,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,3322.0,8745.0,NaN,335.0,719.0,3675.0,1674,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,3358.0,12735.0,NaN,374.0,730.0,4911.0,1722,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,3414.0,NaN,NaN,482.0,795.0,4935.0,2044,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,3528.0,NaN,NaN,503.0,889.0,5010.0,2124,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,3754.0,NaN,NaN,513.0,NaN,5732.0,2162,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,5280.0,NaN,NaN,642.0,NaN,NaN,2174,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,5290.0,NaN,NaN,NaN,NaN,NaN,2388,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,6692.0,NaN,NaN,NaN,NaN,NaN,2426,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,9528.0,NaN,NaN,NaN,NaN,NaN,2604,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,13544.0,NaN,NaN,NaN,NaN,NaN,2616,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,32208.0,NaN,NaN,NaN,NaN,NaN,2644,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2660,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2704,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2752,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2868,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3114,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3216,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3230,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3298,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3768,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5348,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5372,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7020,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7800,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8032,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8120,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20608,NaN,NaN,NaN,NaN,NaN

In [145]:
#для каждого типа контента вычисляю все вышеперечисленные характеристики
#types=(data['Type'].values).tolist()
#unique_types=pandas.unique(types)
#unique_types.tolist()
#for ty in unique_types:
#    print('Mean for Type ',ty,':','\n',data[data['Type']==ty].mean(numeric_only=True),'\n')
#    print('Min for Type ',ty,':','\n',data[data['Type']==ty].min(numeric_only=True),'\n')
#    print('Max for Type ',ty,':','\n',data[data['Type']==ty].max(numeric_only=True),'\n')
#    print('Median for Type ',ty,':','\n',data[data['Type']==ty].median(numeric_only=True),'\n')
#    print('Mode for Type ',ty,':','\n',data[data['Type']==ty].mode(numeric_only=True),'\n')

Для вычисления самого популярного объекта выборки, мне кажется, является логичным вычислить нормализованную сумму признаков, 
начиная с Lifetime Post Total Reach и до конца, так как эти признаки оценивают популярность конкретного объекта среди 
пользователей. Для обработки пропусков я заполняю их средним значение по этому признакому, такой подход позволяет смоделировать
реальную ситуацию и найти наиболее популярный объект. Однако, чтобы удостовериться в правильности выбора объекта, я пробую ниже
еще два варианта заполнения пропусков(максимальными и минимальными значениям). Так же, признаки очень разняться по масштабу, чтобу это не влияло на результат, я нормализую признаки(теперь они все варьируются от 0 до 1).
По каждому из способов 120 объект(начиная с 0) является наиболее популярными.

In [146]:
from sklearn import preprocessing 

data=data.fillna(data.mean(numeric_only=True))

X=data.loc[:,'Lifetime Post Total Reach':'Total Interactions'].values

normalized_X = preprocessing.normalize(X)

popularity=[]
count=0
for i in normalized_X:
    popularity.append(0)
    for j in i:
        popularity[count]+=j
    count+=1

In [147]:
print(popularity.index(max(popularity)),' ',max(popularity))

120   2.4783711416743137

In [148]:
data = pandas.read_csv('dataset_Facebook.csv',sep=';')
data=data.fillna(data.max(numeric_only=True))

X=data.loc[:,'Lifetime Post Total Reach':'Total Interactions'].values

normalized_X = preprocessing.normalize(X)

popularity=[]
count=0
for i in normalized_X:
    popularity.append(0)
    for j in i:
        popularity[count]+=j
    count+=1
print(popularity.index(max(popularity)),' ',max(popularity))

120   2.6542200444962627

In [149]:
data = pandas.read_csv('dataset_Facebook.csv',sep=';')
data=data.fillna(data.min(numeric_only=True))

X=data.loc[:,'Lifetime Post Total Reach':'Total Interactions'].values

normalized_X = preprocessing.normalize(X)

popularity=[]
count=0
for i in normalized_X:
    popularity.append(0)
    for j in i:
        popularity[count]+=j
    count+=1
print(popularity.index(max(popularity)),' ',max(popularity))

120   2.462534960375082